### ISSUE TITLE
std::less_equal need header <functional>

### ISSUE THREAD

**Issue by zxffffffff** [google/snappy#188]
std::less_equal is defined in functional which is missing from snappy.cc

I found this PR: https://github.com/google/snappy/pull/172. Why hasn't it been merged?

That's my error message:
```
[build] E:\work_e\others\snappy\snappy.cc(1233): error C2039: “less_equal”: 不是“std”的成员 [E:\work_e\others\snappy\build\snappy.vcxproj]
[build]   C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(17): note: 参见“std”的声明
[build] E:\work_e\others\snappy\snappy.cc(1233): error C2065: “less_equal”: 未声明的标识符 [E:\work_e\others\snappy\build\snappy.vcxproj]
[build] E:\work_e\others\snappy\snappy.cc(1233): error C2059: 语法错误:“const” [E:\work_e\others\snappy\build\snappy.vcxproj]
```

**Comment by danilak-G** [comment]
It was not merged because this project does not have proper staffing

Fixed with https://github.com/google/snappy/commit/58d911b2841fead6ad3aedc82367ffbf3a5af8f1, will be in 1.2.2
